dependencies {
    compileOnly('com.github.GTNewHorizons:BuildCraft:7.1.57:api') { transitive = false }
    compileOnly('com.github.GTNewHorizons:EnderIO:2.10.25:dev') { transitive = false }
    compileOnly('com.github.GTNewHorizons:NotEnoughItems:2.8.93-GTNH:dev') { transitive = false }
    compileOnly('com.github.GTNewHorizons:waila:1.19.23:api') { transitive = false }
    compileOnly('curse.maven:agricraft-225635:2284133-sources')
    compileOnly('curse.maven:cofh-lib-220333:2388748')
    compileOnly('igwmod:IGW-Mod-1.7.10:1.1.12-34:userdev') { transitive = false }
    compileOnly('net.industrial-craft:industrialcraft-2:2.2.828-experimental:api')
}
